apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: apps
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQxMjM=  # password123 in base64
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: apps
  labels:
    app: db
    tier: backend
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
        tier: backend
    spec:
      containers:
      - name: postgres
        image: postgres:15
        envFrom:
        - secretRef:
            name: postgres-secret
        ports:
        - containerPort: 5432  # Changed to default Postgres port
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
      storageClassName: standard
