apiVersion: v1
kind: Namespace
metadata:
  name: perf-test
  labels:
    purpose: performance-testing
    app: wake-perf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: perf-config
  namespace: perf-test
data:
  LOG_RATE: "500"  # logs per second per container (base rate)
  LOG_PATTERN_COUNT: "10"  # number of different log patterns
  BURST_MODE: "true"  # enable burst logging for 10k+ logs/sec
  MEMORY_STRESS: "true"  # enable memory allocation stress
  HIGH_THROUGHPUT: "true"  # enable high-throughput mode