apiVersion: v1
kind: Namespace
metadata:
  name: perf-test
  labels:
    purpose: performance-testing
    app: wake-perf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: perf-config
  namespace: perf-test
data:
  LOG_RATE: "100"  # logs per second per container
  LOG_PATTERN_COUNT: "5"  # number of different log patterns
  BURST_MODE: "false"  # enable burst logging
  MEMORY_STRESS: "false"  # enable memory allocation stress